labels: [ "type: feature" ]

body:
  - type: markdown
    attributes:
      value: |
        It is recommended that you search all open discussions to avoid duplicate feature requests. If one exists, Please reply to that one if you have anything to add.
        Before requesting a feature, You must make sure you are using 1.20.4 or whatever is the latest version Mojang released and that the feature doesn't already exist.

  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: "A clear and concise description of what the feature is."
      placeholder: "I want a pony for Christmas!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add any other context or screenshots about the feature request below.
    validations:
      required: false