[plugins]
# Paperweight
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Paper API
paper = "1.21.4-R0.1-SNAPSHOT"
minecraft = "1.21.4"

# Gradle Plugins
shadow = "9.0.0-beta12"
paperweight = "2.0.0-beta.10"
runPaper = "2.3.1"
minotaur = "2.8.7"
hangar = "0.1.2"

# Plugins
placeholderapi = "2.11.6"

# Fusion API
fusion = "1.2.0"

# Common API
jetbrains = "24.1.0"
bStats = "3.1.0"

# Kyori API
adventure = "4.20.0"

[libraries]
# Paper API
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori API
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Bukkit Plugins API
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

metrics = { module = "org.bstats:bstats-bukkit", version.ref = "bStats" }

# Pl3xMap API
pl3xmap = { group = "maven.modrinth", name = "pl3xmap", version = "1.21-507" }

# Fusion Core API
fusion-paper = { module = "com.ryderbelserion.fusion:fusion-paper", version.ref = "fusion" }
fusion-core = { module = "com.ryderbelserion.fusion:fusion-core", version.ref = "fusion" }

# Common API
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

[bundles]
# Shared with the git submodules
shared = ["placeholderapi"]

# Adventure API
adventure = ["kyori-api", "kyori-text", "kyori-logger"]