[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[versions]
# Minecraft
paper = "1.21-R0.1-SNAPSHOT"
minecraft = "1.21"

# Libraries
jetbrains = "24.1.0"

# Paper
paperweight = "1.7.1"
runPaper = "2.3.0"
hangar = "0.1.2"

# Other
shadowJar = "8.1.7"

# Modrinth
minotaur = "2.+"

[libraries]
pl3xmap = { group = "maven.modrinth", name = "pl3xmap", version = "1.21-500" }

jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }