name: '${name}'
main: '${group}.${name}'

version: '${version}'
api-version: '${minecraft}'
description: '${description}'

dependencies:
  server:
    Pl3xMap:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true